# Generated by Django 3.0.7 on 2020-06-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200602_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
